module.exports = {
  config: {
    name: "groupreport",
    aliases: ["grpreport", "grpstats"],
    version: "1.0",
    author: "Azad Vai",
    role: 0,
    shortDescription: "Group activity report",
    longDescription: "Gives fake group stats like top sender, mood etc",
    category: "group",
    guide: "{pn}"
  },

  onStart: async function ({ api, event, usersData, threadsData }) {
    const threadID = event.threadID;

    // Group Info
    const threadInfo = await threadsData.get(threadID);
    const groupName = threadInfo.threadName || "This Group";
    const members = threadInfo.members || {};

    // Fake stats generator
    const getRandom = (min, max) => Math.floor(Math.random() * (max - min + 1)) + min;

    // Top sender
    const memberIDs = Object.keys(members);
    const topID = memberIDs[Math.floor(Math.random() * memberIDs.length)];
    const topName = await usersData.getName(topID);

    // Other fake stats
    const totalMessages = getRandom(300, 1500);
    const mostUsedWords = ["Bro", "Tumpa", "Hmm", "😂", "Bot", "Azad"];
    const moodOptions = ["🔥 Hyper", "😴 Sleepy", "😂 Funny", "😡 Toxic", "📉 Silent"];

    const usedWord = mostUsedWords[Math.floor(Math.random() * mostUsedWords.length)];
    const mood = moodOptions[Math.floor(Math.random() * moodOptions.length)];

    const time = new Date().toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit" });

    const msg = `
📊 Group Report: ${groupName}
━━━━━━━━━━━━━━━━━━
🧮 Total Messages (Today): ${totalMessages}
🏆 Top Sender: ${topName}
💬 Most Used Word: "${usedWord}"
📡 Group Mood: ${mood}
🕒 Generated at: ${time}
━━━━━━━━━━━━━━━━━━
⚠️ Note: This is a fake fun report generated by bot.
    `.trim();

    api.sendMessage(msg, threadID);
  }
};
